"""
seed_status_rules.py
====================
Loads 05_STATUS_RULES into the database.
Run from backend/ folder:
    python seed_status_rules.py

Safe to re-run — clears and reloads all status rules each time.
"""

import sys, os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database import SessionLocal
from app.models import StatusRule
from datetime import date

db = SessionLocal()

# Clear existing rules
deleted = db.query(StatusRule).delete()
db.commit()
print(f"Cleared {deleted} existing status rules\n")

STATUS_RULES = [
    {
        "status_value":           "Closed - Visa granted, then enrolled",
        "is_eligible":            True,
        "counts_as_enrolled":     True,
        "coun_pct":               1.0,
        "co_direct_pct":          1.0,
        "co_sub_pct":             1.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          True,
        "requires_enrol":         True,
        "dedup_rank":             5,
        "note":                   "Full bonus both roles",
    },
    {
        "status_value":           "Closed - Visa granted (visa only)",
        "is_eligible":            True,
        "counts_as_enrolled":     False,
        "coun_pct":               1.0,
        "co_direct_pct":          1.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          True,
        "requires_enrol":         False,
        "dedup_rank":             5,
        "note":                   "CO Sub gets no bonus — visa service only",
    },
    {
        "status_value":           "Closed - Visa granted then cancelled",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": True,
        "requires_visa":          True,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "0 bonus direct. MA/GROUP/OOS: 400k fees-paid rate",
    },
    {
        "status_value":           "Closed - Visa refused",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": True,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "0 bonus direct. MA/GROUP/OOS: 400k fees-paid rate",
    },
    {
        "status_value":           "Closed - Visa refused then granted",
        "is_eligible":            True,
        "counts_as_enrolled":     True,
        "coun_pct":               1.0,
        "co_direct_pct":          1.0,
        "co_sub_pct":             1.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          True,
        "requires_enrol":         True,
        "dedup_rank":             5,
        "note":                   "Full bonus — visa ultimately approved",
    },
    {
        "status_value":           "Closed - Enrolment (only)",
        "is_eligible":            True,
        "counts_as_enrolled":     True,
        "coun_pct":               1.0,
        "co_direct_pct":          1.0,
        "co_sub_pct":             1.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         True,
        "dedup_rank":             4,
        "note":                   "Full bonus — e.g. Vietnam domestic, enrolment-only program",
    },
    {
        "status_value":           "Closed - Enrolled then cancelled",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          True,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "Zero bonus all roles — student withdrew after enrolment",
    },
    {
        "status_value":           "Closed - Enrolled, then Visa granted",
        "is_eligible":            True,
        "counts_as_enrolled":     True,
        "coun_pct":               0.0,
        "co_direct_pct":          0.5,
        "co_sub_pct":             0.5,
        "is_carry_over":          True,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          True,
        "requires_enrol":         True,
        "dedup_rank":             3,
        "note":                   "IsCarryOver=Y. Counsellor 0% (paid 100% last month). CO receives remaining 50%.",
    },
    {
        "status_value":           "Closed - Cancelled",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": True,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "0 bonus direct. MA/GROUP/OOS: 400k fees-paid rate",
    },
    {
        "status_value":           "Current - Enrolled",
        "is_eligible":            True,
        "counts_as_enrolled":     True,
        "coun_pct":               1.0,
        "co_direct_pct":          0.5,
        "co_sub_pct":             0.5,
        "is_carry_over":          False,
        "is_current_enrolled":    True,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         True,
        "dedup_rank":             2,
        "note":                   "IsCurrentEnrolled=Y. Counsellor 100% now. CO 50% now, remaining 50% when visa confirmed.",
    },
    {
        "status_value":           "Current - Visa refused",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          True,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "Zero bonus — no fees collected",
    },
    {
        "status_value":           "Pending - Visa refused",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          True,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "Zero bonus — no fees collected",
    },
    {
        "status_value":           "Closed - Institution refused",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          True,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "Zero bonus — institution declined application",
    },
    {
        "status_value":           "Closed - Visa granted",
        "is_eligible":            True,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.5,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": True,
        "requires_visa":          True,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "FeesPaidNonEnrolled=Y. CO Direct 50%. Engine uses ClientType for context.",
    },
    {
        "status_value":           "Closed - Enrolled then visa refused",
        "is_eligible":            False,
        "counts_as_enrolled":     False,
        "coun_pct":               0.0,
        "co_direct_pct":          0.0,
        "co_sub_pct":             0.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          True,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         False,
        "dedup_rank":             1,
        "note":                   "NEW v6.0. Zero bonus — student enrolled but visa later refused.",
    },
    {
        "status_value":           "Closed - Enrolment",
        "is_eligible":            True,
        "counts_as_enrolled":     True,
        "coun_pct":               1.0,
        "co_direct_pct":          1.0,
        "co_sub_pct":             1.0,
        "is_carry_over":          False,
        "is_current_enrolled":    False,
        "is_zero_bonus":          False,
        "fees_paid_non_enrolled": False,
        "requires_visa":          False,
        "requires_enrol":         True,
        "dedup_rank":             4,
        "note":                   "Full bonus — e.g. Vietnam domestic, enrolment-only program",
    },
]

for rule in STATUS_RULES:
    db.add(StatusRule(**rule))

db.commit()
print(f"✅ Loaded {len(STATUS_RULES)} status rules successfully!")
db.close()
